### PR TITLE
F3 find Total Commander last find text

### LINKED ISSUE #107: SearchString doens't showed by F3 after search files (with text)
How to reproduce.
1. Start search for files and find text.
2. In search results press F3 (start viewer) to View the file.
3. Press F3 again to find in this file.

There is no problem with F7 (Viewer dialog) but your own started with empty string to find.

### PR DESCRIPTION
**Pull request by springsunx**
fix #107

need test.

### CODE REVIEW

**Comment by Alexey-T** [comment]
thanks for your fix, I have no time for the TotalCmd plugin so help was needed. will check it soon.

**Comment by avmaksimov** [comment]
> thanks for your fix, I have no time for the TotalCmd plugin so help was needed. will check it soon.

Please find a little of your precious time for that.

**Comment by avmaksimov** [comment]
I use Double Commander and I see such problem after installing new version.

**Comment by Alexey-T** [comment]
So the patch was not suitable for DoubleCmd. Env variables names etc.

**Comment by mpszczolka** [comment]
Tested fix in TotalCommander (10.52) - works fine.
Big thanks.

**Pull request merged**
