### PR TITLE
Update form_main.pas

### PR DESCRIPTION
**Pull request by springsunx**
fix Wrong clipboard behaviour #60
Only when paste with the right button.

### CODE REVIEW

**Comment by Alexey-T** [comment]
i dont ssee why it can solve the issue. command AltPaste:
```
    cCommand_ClipboardAltPaste:                 Result:= DoCommand_ClipboardPaste(false, false,
                                                           PrimarySelection.HasFormat(ATEditorOptions.ClipboardColumnFormat),
                                                           PrimarySelection.AsText);
```
so it uses PrimarySelection which is for unix only AFAIR. it's bad on windows.

**Comment by springsunx** [comment]
I test it and success, but use Ctrl+V faild.

**Comment by springsunx** [comment]
image
Maybe it doesn't work here.
I tried to change it to cCommand_ClipboardAltPaste, but it didn't work

**Comment by springsunx** [comment]
Now Ctrl+V is ok.

**Pull request merged**
